"""empty message

Revision ID: 7c7c90adf4b9
Revises: 77e46a475953
Create Date: 2023-11-20 11:10:21.951595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c7c90adf4b9'
down_revision: Union[str, None] = '77e46a475953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder_content', sa.Column('references', sa.Text(), nullable=True))
    op.alter_column('folder_content', 'question',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('folder_content', 'answer',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folder_content', 'answer',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('folder_content', 'question',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=False)
    op.drop_column('folder_content', 'references')
    # ### end Alembic commands ###
